# Generated by Django 4.2.3 on 2024-05-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
    ]
