# Generated by Django 4.2.3 on 2024-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmgmt', '0002_remove_commit_author_remove_pullrequest_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
