# Generated by Django 4.2.3 on 2026-07-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_project_app_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitmgmt', '0004_org_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pullrequestcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='personalaccesstoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='prefix',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft PRs cannot be merged until marked ready.'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository', to='pipeline.application'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
    ]
