# Generated by Django 4.2.3 on 2026-08-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmgmt', '0005_alter_commit_options_alter_pullrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
