# Generated by Django 4.2.3 on 2024-05-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repository_url', models.URLField()),
                ('environment_variables', models.JSONField(blank=True, default=dict)),
                ('build_triggers', models.JSONField(blank=True, default=dict)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('notification_emails', models.CharField(blank=True, max_length=500)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('build_scripts', models.TextField(blank=True)),
                ('test_scripts', models.TextField(blank=True)),
                ('deployment_scripts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipeline.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.TextField()),
                ('condition', models.CharField(choices=[('always', 'Always'), ('on_success', 'On Success'), ('on_failure', 'On Failure')], max_length=100)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline.stage')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('command', models.TextField()),
                ('condition', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.project'),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.project')),
            ],
        ),
    ]
