# Generated by Django 4.2.3 on 2024-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pipeline.tag'),
        ),
    ]
