# Generated by Django 4.2.3 on 2024-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_pipelinerun_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='run_id',
        ),
    ]
