# Generated by Django 4.2.3 on 2026-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_deploytarget_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymenttarget',
            name='endpoint',
            field=models.CharField(blank=True, help_text='Cluster URL, registry host, SSH host, etc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='deploymenttarget',
            name='namespace',
            field=models.CharField(blank=True, help_text='K8s namespace / ECS cluster / resource group', max_length=100),
        ),
        migrations.AlterField(
            model_name='deploymenttarget',
            name='region',
            field=models.CharField(blank=True, help_text='AWS/Azure/GCP region', max_length=100),
        ),
    ]
