# Generated by Django 4.2.3 on 2026-07-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_alter_deploymenttarget_endpoint_and_more'),
        ('pipeline', '0005_buildartifact_notification_models'),
    ]

    operations = [
    ]
