# Generated by Django 4.2.3 on 2024-05-22 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_pipelinerun_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='run_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
