# Generated by Django 4.2.3 on 2026-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_agenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='timeout',
            field=models.IntegerField(default=60, help_text='Step execution timeout in seconds'),
        ),
    ]
