# Generated by Django 4.2.3 on 2024-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_alter_pipelinerun_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('registration_status', models.BooleanField(default=False)),
            ],
        ),
    ]
