# Generated by Django 4.2.3 on 2024-05-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='registration_status',
        ),
        migrations.AddField(
            model_name='agent',
            name='hash_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.agent')),
            ],
        ),
    ]
