# Generated by Django 4.2.3 on 2024-05-22 10:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_remove_agent_registration_status_agent_hash_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agent',
            name='hash_key',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='hostname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ip_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
    ]
