# Generated by Django 4.2.3 on 2024-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_command_timestamp_alter_agent_hash_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
