# Generated by Django 4.2.3 on 2024-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_agent_last_heartbeat_agent_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
