# Generated by Django 4.2.3 on 2024-05-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_globalcredential_localcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.agent'),
        ),
    ]
