# Generated by Django 4.2.3 on 2024-05-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_pipelinerun_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agents', models.ManyToManyField(related_name='applications', to='pipeline.agent')),
                ('global_credentials', models.ManyToManyField(related_name='applications', to='pipeline.globalcredential')),
                ('local_credentials', models.ManyToManyField(related_name='applications', to='pipeline.localcredential')),
                ('pipelines', models.ManyToManyField(related_name='applications', to='pipeline.pipeline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pipeline.project')),
            ],
        ),
    ]
