# Generated by Django 4.2.3 on 2024-05-24 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamlFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('yaml_content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.project')),
            ],
        ),
    ]
