# urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', login_required(views.DashboardView.as_view()), name='dashboard'),
    path('settings/', login_required(views.global_settings), name='global_settings'),
    path('projectslist', login_required(views.project_list), name='project_list'),
    path('projects/<str:project_name>/', login_required(views.project_detail), name='project_detail'),
    path('projects/new/', login_required(views.project_create), name='project_create'),
    path('projects/<str:project_name>/edit/', login_required(views.project_edit), name='project_edit'),
    path('projects/<str:project_name>/delete/', login_required(views.project_delete), name='project_delete'),
    path('projects/<str:project_name>/trigger_build/', login_required(views.trigger_build), name='trigger_build'),
    path('github_webhook/', views.github_webhook, name='github_webhook'),
    path('pipeline/builds/<int:build_id>/download/', login_required(views.download_log), name='download_log'),
    path('projects/<str:project_name>/configure/', login_required(views.configure_project), name='configure_project'),
    path('projects/<str:project_name>/build_history/', login_required(views.build_history), name='build_history'),
    path('projects/<str:project_name>/pipelines/', login_required(views.pipeline_list), name='pipeline_list'),
    path('projects/<str:project_name>/pipelines/create/', login_required(views.pipeline_create), name='pipeline_create'),
    path('projects/<str:project_name>/pipelines/<str:pipeline_name>/update/', login_required(views.pipeline_update), name='pipeline_update'),
    path('projects/<str:project_name>/pipelines/<str:pipeline_name>/delete/', login_required(views.pipeline_delete), name='pipeline_delete'),
    path('pipeline/<str:pipeline_name>/', login_required(views.pipeline_detail), name='pipeline_detail'),
    path('pipelines/<str:pipeline_name>/steps/', login_required(views.pipeline_step_list), name='pipeline_step_list'),
    path('pipelines/<str:pipeline_name>/steps/create/', login_required(views.pipeline_step_create), name='pipeline_step_create'),
    path('pipelines/<str:pipeline_name>/steps/<int:step_id>/update/', login_required(views.pipeline_step_update), name='pipeline_step_update'),
    path('pipelines/<str:pipeline_name>/steps/<int:step_id>/delete/', login_required(views.pipeline_step_delete), name='pipeline_step_delete'),
    path('pipeline/<str:pipeline_name>/run/', login_required(views.run_pipeline), name='run_pipeline'),
    path('pipeline/run/<uuid:run_id>/', login_required(views.pipeline_run_detail), name='pipeline_run_detail'),
    path('agents/', login_required(views.agent_list), name='agent_list'),
    path('agents/<str:agent_hostname>/', login_required(views.agent_detail), name='agent_detail'),
    path('agents/add/', login_required(views.add_agent), name='add_agent'),
    path('agents/send-command/', login_required(views.send_command), name='send_command'),
    path('agents/register/', views.register_agent, name='register_agent'),
    path('agents/receive-heartbeat/', views.receive_heartbeat, name='receive_heartbeat'),
    path('agents/receive-command/', views.receive_command, name='receive_command'),
    path('agents/instructions/', login_required(views.agent_instructions), name='agent_instructions'),
    path('global_credentials /', login_required(views.global_credential_list), name='global_credential_list'),
    path('global_credentials/create/', login_required(views.global_credential_create), name='global_credential_create'),
    path('global_credentials/<int:pk>/', login_required(views.global_credential_detail), name='global_credential_detail'),
    path('global_credentials/<int:pk>/update/', login_required(views.global_credential_update), name='global_credential_update'),
    path('global_credentials/<int:pk>/delete/', login_required(views.global_credential_delete), name='global_credential_delete'),
    
    # Local credentials URLs
    path('projects/<str:project_name>/local_credentials/', login_required(views.local_credential_list), name='local_credential_list'),
    path('projects/<str:project_name>/local_credentials/create/', login_required(views.local_credential_create), name='local_credential_create'),
    path('local_credentials/<int:pk>/', login_required(views.local_credential_detail), name='local_credential_detail'),
    path('local_credentials/<int:pk>/update/', login_required(views.local_credential_update), name='local_credential_update'),
    path('local_credentials/<int:pk>/delete/', login_required(views.local_credential_delete), name='local_credential_delete'),
    path('project/<str:project_name>/create_application/', login_required(views.create_application), name='create_application'),
    path('applications/<str:application_name>/', login_required(views.application_detail), name='application_detail'),
]
